---
- name: copy installer script template
  copy:
    src: files/conda_pkg_install.sh.j2
    dest: "{{ tmpdir }}"
    mode: 0644

- name: generate installer script
  template:
    src: "{{ tmpdir }}/conda_pkg_install.sh.j2"
    dest: "{{ tmpdir }}/conda_pkg_install.sh"
    owner: ubuntu
    group: ubuntu
    mode: 0755
-
  name: install-miniconda
  become: yes
  become_user: ubuntu
  command: bash {{ tmpdir }}/conda_pkg_install.sh

  
